# Generated by Django 4.1.6 on 2023-02-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', through='musicplatform.SongsPlaylists', to='musicplatform.songs'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='date',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
