# Generated by Django 4.1.6 on 2023-03-19 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicplatform', '0002_playlists_songs_alter_songs_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albums',
            options={'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='artists',
            options={'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='playlists',
            options={'verbose_name_plural': 'Playlists'},
        ),
        migrations.AlterModelOptions(
            name='songs',
            options={'verbose_name_plural': 'Songs'},
        ),
        migrations.AlterModelOptions(
            name='songsartists',
            options={'verbose_name_plural': 'Songs artists'},
        ),
        migrations.AlterModelOptions(
            name='songsplaylists',
            options={'verbose_name_plural': 'Songs playlists'},
        ),
        migrations.AlterField(
            model_name='songs',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='musicplatform.albums'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='musicplatform.genres'),
        ),
    ]
