version: '3'

services:
  django:
    build: .
    container_name: musicplatform
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - ./.env_file
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=os.getenv('SQL_USER')
      - POSTGRES_PASSWORD=os.getenv('SQL_PASSWORD')
      - POSTGRES_DB=os.getenv('SQL_DB')
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: